<p>IMPORTANT! AS WITH ALL CONTRACTS, IF YOU ARE UNDER THE AGE OF 18, YOU MUST HAVE YOUR PARENT OR GUARDIAN READ THE AGREEMENT BELOW AND AGREE TO IT FOR YOU. IF YOU DON'T GET YOUR PARENT OR GUARDIAN TO READ AND AGREE TO THIS, YOU DON'T HAVE PERMISSION TO USE THIS SITE. ALWAYS GET AN ADULT'S PERMISSION BEFORE GOING ONLINE.</p> 
    <p>PLEASE READ THESE TERMS OF USE ("AGREEMENT") CAREFULLY BEFORE USING THE SERVICES OFFERED BY CLASSCONNECT, INC. ("COMPANY"). BY VISITING THE WEBSITES OR USING THE SERVICES IN ANY MANNER, YOU AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY AND A PARTY TO THE TERMS AND CONDITIONS OF THIS AGREEMENT TO THE EXCLUSION OF ALL OTHER TERMS. IF THE TERMS OF THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. IF YOU DO NOT UNCONDITIONALLY AGREE TO ALL THE TERMS AND CONDITIONS OF THE AGREEMENT, YOU HAVE NO RIGHT TO USE THE WEBSITE OR SERVICES. USE OF COMPANY'S SERVICES IS EXPRESSLY CONDITIONED UPON YOUR ASSENT TO ALL THE TERMS AND CONDITIONS OF THIS AGREEMENT, TO THE EXCLUSION OF ALL OTHER TERMS.</p> 
    <p>1. ACCESS TO THE SERVICES</p> 
    <p>The classconnect.com website and domain name and all other websites and domain names affiliated with Company, and any other linked pages, features, content, or application services offered from time to time by Company in connection therewith (collectively, the "Website") are owned or operated by Company. Subject to the terms and conditions of this Agreement, Company may offer to provide certain services described more fully on the Website ("Services"), that you select through the process provided on the Website, solely for your own, personal use, and not for the benefit of any third party. The term "Services" shall include, without limitation, any service Company performs for you and the content offered by Company on the Website. Company may change, suspend or discontinue all or any part of the Services at any time. Company also may impose limits on certain features and services or restrict your access to parts or all of the Services without notice or liability. You understand and agree that the Services are provided on an AS IS and AS AVAILABLE basis. Company expressly and completely disclaims any and all responsibility and liability for the availability, accuracy, timeliness, security or reliability of the Services. Company also reserves the right to modify, suspend or discontinue Services at any time and for any or no reason, with or without notice, and without any liability to you. Company reserves the right, in its sole discretion, to modify this Agreement at any time by posting a notice on the Website, or by sending you a notice via email. You shall be responsible for reviewing and becoming familiar with any such modifications. Your use of the Services or the Website following such notification constitutes your acceptance of the terms and conditions of this Agreement as modified.</p> 
    <p>You represent and warrant to Company that: (i) you are an individual (i.e., not a corporation) and you are of legal age to form a binding contract (or, if you are a minor, you have your parent's permission to use the Services, and your parent has read and agrees to this Agreement on your behalf); (ii) all registration information you submit is accurate and truthful; (iii) you will maintain the accuracy of such information; (iv) if you are accepting this Agreement on behalf of an institution, company or other legal entity, you have the authority to bind that institution, company or legal entity to this Agreement. You also certify that you are legally permitted to use and access the Services and take full responsibility for the selection and use of and access to the Services. This Agreement is void where prohibited by law, and the right to access the Services is revoked in such jurisdictions.</p> 
    <p>You shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access, or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. You shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services.</p> 
    <p>2. PROPER USE</p> 
    <p> 
      You agree that you are responsible for your own communications and for any consequences thereof. Your use of the Services is subject to your acceptance of and compliance with the Agreement, including the ClassConnect
      <a href="/legal/privacy">Privacy Policy</a> 
      , located at
      <a href="/legal/privacy">http://classconnect.com/legal/privacy</a> 
      , or such other URL as ClassConnect may provide from time to time. You agree that you will use the Services in compliance with all applicable local, state, national, and international laws, rules and regulations, including any laws regarding the transmission of technical data exported from your country of residence. You shall not, shall not agree to, and shall not authorize or encourage any third party to: (i) use the Services to upload, transmit or otherwise distribute any content that is unlawful, defamatory, harassing, abusive, fraudulent, obscene, contains viruses, or is otherwise objectionable as reasonably determined by ClassConnect; (ii) upload, transmit or otherwise distribute content that infringes upon another party's intellectual property rights or other proprietary, contractual or fiduciary rights or obligations; (iii) prevent others from using the Services in a manner consistent with this Agreement; or (iv) use the Services for any fraudulent or inappropriate purpose. Violation of any of the foregoing may result in immediate termination of your account, revocation of your ability to use the Services, and may subject you to state and federal penalties and other legal consequences. ClassConnect reserves the right, but shall have no obligation, to investigate your use of the Services in order to determine whether a violation of the Agreement has occurred or to comply with any applicable law, regulation, legal process or governmental request.
    </p> 
    <p>3. RESPONSIBILITY FOR FEES AND USAGE CHARGES</p> 
    <p>By utilizing the Service, you acknowledge that you may receive e-mail or text messages on your phone or mobile communications device, and that the receipt of such messages may cause you to incur usage charges or other fees or costs in accordance with your wireless or data service plan. Any and all such charges, fees, or costs are your sole responsibility. You should consult with your wireless carrier to determine what rates, charges, fees, or costs may apply to your use of the Services.</p> 
    <p>4. USE BY CHILDREN</p> 
    <p>Company collects limited personal information from minor students, but only where that student's school, district, and/or teacher has contracted with Company to collect personal information from students for the use and benefit of the learning environment. Company requires schools, districts, and/or teachers to obtain parental consent from students' parents before collecting any such personal information. If you are a student, please do not send any personal information about yourself to us, other than what we request from you when you sign up for the Services. In the event that we learn that we have collected personal information from a student without parental consent being obtained by his or her school, district, and/or teacher, or if we learn a student has provided us personal information beyond what we request when he or she signs up for the Website, we will delete that information as quickly as possible. If you believe that a student may have provided us personal information beyond what is requested when signing up for the Website, or that a student's school, district, or teacher has not required parental consent prior to our collection of any personal information, please contact us at support@classconnect.com.</p> 
    <p>5. ADDITIONAL TERMS</p> 
    <p> 
      (a) For information regarding Company's treatment of personally identifiable information, please review Company's current Privacy Policy at
      <a href="/legal/privacy">http://classconnect.com/legal/privacy</a> 
      , which is hereby incorporated into this Agreement by reference.
    </p> 
    <p>(b) If you are a student, the following terms also apply to you:</p> 
    <p>(i) Remember, you must get your parent or guardian to read this Agreement before using the Website.</p> 
    <p>(ii) You will only register for and access the Services as a student registrant, and not as a teacher, school, district, parent, publisher, or any other category of user, whether offered by Company now or in the future.</p> 
    <p>(iii) You will only access the Services using the access code given to you by your teacher. You may not use any access codes which you receive from other students or which you did not directly receive from your own teacher.</p> 
    <p>(c) If you are accessing the Services on behalf of a school or district, the following terms also apply to you:</p> 
    <p> 
      (i) You represent and warrant that you are solely responsible for complying with the Child Online Privacy Protection Act ("COPPA"), which requires parental consent for online collection of personal information from children under 13. You must obtain advance written consent ("Consent") from all parents whose children will be accessing the Services. When obtaining Consent, you must provide parents with a copy of our
      <a href="/legal/privacy">Privacy Policy</a> 
      <a href="/legal/privacy">http://classconnect.com/legal/privacy</a> 
      . You must keep signed Consents on file and provide them to Company upon our request. For more information on COPPA, please see
      <a href="http://www.ftc.gov/privacy">www.ftc.gov/privacy.</a> 
    </p> 
    <p>(ii) You will only grant access codes to teachers and staff members who are current employees of your school or district. Upon termination of a teacher or other staff member's employment with you, you will require such individual to return and cease using all access codes he or she has in his or her possession. If at any time you learn a user of the Services claims to be affiliated with your school or district who is not, in fact, affiliated with your school or district, you will notify Company immediately.</p> 
    <p>(iii) On all school computers that are accessible to students, you will redirect the domain "classconnect.com" to the unique Company domain that has been assigned to your school or district.</p> 
    <p>(d) If you are accessing the Services as a teacher, the following terms also apply to you:</p> 
    <p>(i) You represent and warrant that you have permission from your school and/or district to enter into this Agreement and to use the Services as part of your curriculum. You further represent and warrant that you are entering into this Agreement on behalf of your school and/or district, and that you have authority to bind your school and/or district to the terms of this Agreement.</p> 
    <p> 
      (ii) You represent and warrant that you are solely responsible for complying with COPPA, which requires parental consent for online collection of personal information from children under 13. You must obtain Consent from all parents whose children will be accessing the Services. When obtaining Consent, you must provide parents with a copy of our
      <a href="/legal/privacy">Privacy Policy</a> 
      <a href="/legal/privacy">http://classconnect.com/legal/privacy.</a> 
      You must keep signed Consents on file and provide them to Company upon our request. For more information on COPPA, please see
      <a href="http://www.ftc.gov/privacy">www.ftc.gov/privacy.</a> 
    </p> 
    <p>(e) If you are accessing the Services as a publisher, the following terms also apply to you:</p> 
    <p>(i) You understand that the content you contribute to the Services as a publisher will be considered a User Submission under Section 4 of this Agreement.</p> 
    <p>(f) Company will provide you with a "Partner Page" on the Website where you may post all your User Submissions.</p> 
    <p>(g) If you are accessing the Services as a parent, the following terms also apply to you:</p> 
    <p>(i) You will only use the parent code(s) provided to you by your child or children's teacher(s). You agree not to use any access code to access the account or information about anyone other than the child for whom the access code was provided.</p> 
    <p>(ii) You understand that your acceptance of this Agreement indicates that you are agreeing to these terms both on your own behalf as well as on behalf of your child or children who use the Website. Children under 18 must not use the Website, however, until after a parent has accepted this Agreement on their behalf.</p> 
    <p>6. WEBSITE CONTENT</p> 
    <p>The Website and its contents are intended solely for the personal, non-commercial use of Website users and may only be used in accordance with the terms of this Agreement. All materials displayed or performed on the Website (including, but not limited to text, graphics, articles, photographs, images, illustrations (also known as the "Content")) are protected by copyright and other intellectual property laws. You shall abide by all copyright notices, trademark rules, information, and restrictions contained in any Content accessed through the Services, and shall not use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purposes whatsoever any Content or third party submissions or other proprietary rights not owned by you: (i) without the express prior written consent of the respective owners, and (ii) in any way that violates any third party right.</p> 
    <p>The Website is protected by copyright as a collective work and/or compilation, pursuant to U.S. copyright laws, international conventions, and other copyright laws. You may not modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section 4), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.</p> 
    <p>You may download or copy the Content (and other items displayed on the Website for download) for personal non-commercial use only, provided that you maintain all copyright and other notices contained in such Content. You shall not store any significant portion of any Content in any form. Copying or storing of any Content other than personal, noncommercial use is expressly prohibited without prior written permission from Company or from the copyright holder identified in such Content's copyright notice. You shall not link to the Website without Company's prior written consent, except in accordance with the terms of this Agreement.</p> 
    <p> 
      In the course of using the Services, you and other users may provide information which may be used by Company in connection with the Services and which may be visible to certain other users. You understand that by posting information or content on the Website or otherwise providing content, materials or information to Company or in connection with the Services (collectively, "User Submissions"), Company hereby is and shall be granted a non exclusive, worldwide, royalty free, perpetual, irrevocable, and transferable right to fully exploit such User Submissions (including all related intellectual property rights) and to allow others to do so; however, Company will only share your personally identifiable information in accordance with Company's current
      <a href="/legal/privacy">privacy policy</a> 
      at
      <a href="/legal/privacy">http://classconnect.com/legal/privacy.</a> 
      You also hereby do and shall grant each user of the Services a non-exclusive license to access your User Submissions through the Services, and to use, modify, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Services and under this Agreement. Furthermore, you understand that Company retains the right to reformat, modify, create derivative works of, excerpt, and translate any User Submissions submitted by you. You understand that all information publicly posted or privately transmitted through the Services is the sole responsibility of the person from which such content originated and that Company will not be liable for any errors or omissions in any content. You understand that Company cannot guarantee the identity of any other users with whom you may interact in the course of using the Services. Additionally, Company cannot guarantee the authenticity of any data which users may provide about themselves. You acknowledge that all Content accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to any party resulting therefrom.
    </p> 
    <p>Under no circumstances will Company be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred in connection with use of or exposure to any Content posted, emailed, accessed, transmitted, or otherwise made available via the Services.</p> 
    <p>7. YOUR WARRANTY</p> 
    <p>You warrant, represent and agree that you will not contribute any Content or otherwise use the Services in a manner that (i) infringes or violates the intellectual property rights or proprietary rights, rights of publicity or privacy, or other rights of any third party; (ii) violates any law, statute, ordinance or regulation; (iii) is harmful, fraudulent, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, or otherwise objectionable; or (iv) jeopardizes the security of your account in any way, such as allowing someone else access to your account or password. Company reserves the right to remove any Content from the Services at any time, for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if Company is concerned that you may have breached the immediately preceding sentence), or for no reason at all. You, not Company, remain solely responsible for all Content that you upload, post, email, transmit, or otherwise disseminate using, or in connection with, the Services, and you warrant that you possess all rights necessary to provide such content to Company and to grant Company the rights to use such information in connection with the Services and as otherwise provided herein.</p> 
    <p>8. RESTRICTIONS</p> 
    <p>You are responsible for all of your activity in connection with the Services. Any fraudulent, abusive, or otherwise illegal activity may be grounds for termination of your right to access or use the Services. You may not post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, account, or private information from any Company user. Use of the Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material (including material that may be considered threatening or obscene), or engage in any kind of illegal activity is expressly prohibited. You will not run Maillist, Listserv, any form of auto-responder, or "spam" on the Services, or any processes that run or are activated while you are not logged on to the Website, or that otherwise interfere with the proper working of or place an unreasonable load on the Services' infrastructure. Further, the use of manual or automated software, devices, or other processes to "crawl" or "spider" any page of the Website is strictly prohibited. You will not decompile, reverse engineer, or otherwise attempt to obtain the source code of the Services. You will be responsible for withholding, filing, and reporting all taxes, duties and other governmental assessments associated with your activity in connection with the Services. You may not transfer your account to anyone without express prior written consent of Company.</p> 
    <p>9. WARRANTY DISCLAIMER</p> 
    <p>Company has no special relationship with or fiduciary duty to you. You acknowledge that Company has no control over, and no duty to take any action regarding: which users gains access to the Services; what Content you accesses via the Services; what effects the Content may have on you; how you may interpret or use the Content; or what actions you may take as a result of having been exposed to the Content. You release Company from all liability for you having acquired or not acquired Content through the Services. The Services may contain, or direct you to websites containing, information that some people may find offensive or inappropriate. Company makes no representations concerning any content contained in or accessed through the Services, and Company will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Services. Company makes no representations or warranties regarding suggestions or recommendations of services or products (including Content provided by publishers) offered or purchased through the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) the Services are provided "AS IS" without any warranty of any kind from Company or others unless, with respect to others (only), otherwise made expressly and unambiguously in writing by a designated third party for a specific product. THE SERVICES, CONTENT, WEBSITE AND ANY SOFTWARE ARE PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p> 
    <p>10. REGISTRATION AND SECURITY</p> 
    <p>As a condition to using Services, you may be required to register with Company and select a password and user name ("Company User ID"). You shall provide Company with accurate, complete, and updated registration information. Failure to do so shall constitute a breach of this Agreement, which may result in immediate termination of your account. You may not (i) select or use as a Company User ID a name of another person with the intent to impersonate that person; or (ii) use as a Company User ID a name subject to any rights of a person other than you without appropriate authorization. Company reserves the right to refuse registration of or cancel a Company User ID in its discretion. You shall be responsible for maintaining the confidentiality of your password.</p> 
    <p>11. INDEMNITY</p> 
    <p>You will indemnify and hold Company, its parents, subsidiaries, affiliates, officers, and employees harmless (including, without limitation, from all damages, liabilities, settlements, costs and attorneys' fees) from any claim or demand made by any third party due to or arising out of your access to the Services, use of the Services, your violation of this Agreement, or the infringement by you or any third party using your account of any intellectual property or other right of any person or entity.</p> 
    <p>12. FEES AND PAYMENT</p> 
    <p>Access to the Services is free, but in the future, we may offer special features (including, without limitation, exclusive Content) which Company may charge for. Therefore, Company reserves the right to require payment of fees for certain Services. If you want access to those Services, you shall pay all applicable fees for those Services, as will be described on the Website. Company reserves the right to change its price list for certain Services and to institute new charges at any time, upon notice to you, which may be sent by email or posted on the Website. If you continue to use those Services following such notification, that use constitutes your acceptance of any new or increased charges.</p> 
    <p>13. THIRD PARTY WEBSITES</p> 
    <p>The Services may contain links to third party websites that are not owned or controlled by Company. When you access third party websites, you do so at your own risk. Company encourages you to be aware when you leave the Website and to read the terms and conditions and privacy policy of each third party website that you visit. Company has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites. In addition, Company will not and cannot monitor, verify, censor or edit the content of any third party site. By using the Services, you expressly relieve and hold harmless Company from any and all liability arising from your use of any third party website. Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Company shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you understand and agree that Company is under no obligation to become involved. In the event that you have a dispute with one or more other users, you hereby release Company, its officers, employees, agents, and successors in rights from claims, demands, and damages (actual and consequential) of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our service. If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor."</p> 
    <p>14. TERMINATION</p> 
    <p>This Agreement shall remain in full force and effect while you use the Services. You may terminate your use of the Services or your account at any time by contacting us at support@classconnect.com. Company may suspend or terminate your access to the Services, Website or your account at any time, for any reason (without cause or for your violation of any term of this Agreement), and without warning or notice, which may result in the forfeiture and destruction of all information associated with your membership. Upon termination of your account, your right to use the Services, access the Website, and any Content will immediately cease. All provisions of this Agreement which, by their nature, should survive termination, shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability.</p> 
    <p>15. MISCELLANEOUS</p> 
    <p>The failure of either party to exercise, in any respect, any right provided for herein shall not be deemed a waiver of any further rights hereunder. Company shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond Company's reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation (including "line-noise" interference). If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by you except with Company's prior written consent. Company may transfer, assign or delegate this Agreement and its rights and obligations without consent. This Agreement shall be governed by and construed in accordance with the laws of the State of California without regard to the conflict of laws provisions thereof. Any dispute arising from or relating to the subject matter of this Agreement shall be finally settled by arbitration in Santa Clara County, California, using the English language in accordance with the Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. ("JAMS") then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with the Arbitration Rules and Procedures of JAMS. Judgment upon the award so rendered may be entered in a court having jurisdiction, or application may be made to such court for judicial acceptance of any award and an order of enforcement, as the case may be. Notwithstanding the foregoing, each party shall have the right to institute an action in a court of proper jurisdiction for injunctive or other equitable relief pending a final decision by the arbitrator. For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in the United States Federal Courts located in the Northern District of California. Both parties agree that this Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all modifications must be in a writing signed by both parties, except as otherwise provided herein. This Agreement and any subsequent versions of this Agreement posted to the Website will be deemed a writing signed by both parties. No agency, partnership, joint venture, or employment is created as a result of this Agreement and you do not have any authority of any kind to bind Company in any respect whatsoever.</p> 
    <p>16. COPYRIGHT DISPUTE POLICY</p> 
    <p> 
      Company has adopted the following general policy toward copyright infringement in accordance with the Digital Millennium Copyright Act or DMCA (posted at
      <a href="http://www.lcweb.loc.gov/copyright/legislation/dmca.pdf">www.lcweb.loc.gov/copyright/legislation/dmca.pdf</a> 
      ). It is Company's policy to (1) block access to or remove material that it believes in good faith to be copyrighted material that has been illegally copied and distributed by any of our advertisers, affiliates, content providers, members or users; and (2) remove and discontinue service to repeat offenders.
    </p> 
    <p>Effective: August 29, 2011</p>

    </div></div>